## 분석용 기초

### NumPy 계속

In [3]:
# NumPy 로드
import numpy as np

In [9]:
# Python 리스트를 생성 -> 넘파이 배열로 변경
a = [1,3,5,7,9]
na = np.array(a)

In [8]:
a

[1, 3, 5, 7, 9]

In [10]:
print(a)

[1, 3, 5, 7, 9]

In [11]:
na

array([1, 3, 5, 7, 9])

In [12]:
print(na)

[1 3 5 7 9]

In [13]:
nb = np.array([
    [1,2,3],
    [4,5,6]
]) # 2행 3열 2차원 배열

In [15]:
# 2차원 배열 nb의 1번행을 추출
nb[1]

array([4, 5, 6])

In [16]:
nb[1, 2] # nb의 1번행, 2번열을 추출

np.int64(6)

- Python의 기본형 int는 NumPy에서 np.int64형과 동일

In [17]:
nc = np.array([1.2, 2.3, 3.4])
nc[1]

np.float64(2.3)

- Python의 float은 NumPy에서는 np.float64

In [20]:
nb

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
nb.sum() # 행렬 모든 요소 합산

np.int64(21)

In [19]:
nb.sum(axis=0)  # 열 기준으로 합산

array([5, 7, 9])

In [22]:
nb.sum(axis=1)  # 행 기준으로 합산

array([ 6, 15])

In [27]:
# 랜덤 데이터 생성
np.random.rand(5)

array([0.9885121 , 0.29414445, 0.19379165, 0.33170392, 0.0836642 ])

In [38]:
np.random.randint(1, 10, 5)

array([1, 3, 4, 9, 3], dtype=int32)

In [41]:
# 정규화
nd = np.array([10, 20, 30])

normalized = (nd - nd.mean()) / nd.std()
normalized

array([-1.22474487,  0.        ,  1.22474487])

In [43]:
# 점수데이터 합격자만 추출
scores = np.array([50, 80, 90, 60, 30])

scores[scores >= 60]

array([80, 90, 60])

In [45]:
scores.mean()

np.float64(62.0)

- 정리
    - List: 파이썬 for문 사용
    - NumPy: C언어기반 처리

    - **넘파이가 리스트보다 훨씬 빠름**

### Pandas

- 엑셀을 코드로 다루는 도구
- 표 형태의 데이터 처리 가능
- 데이터분석시 가장 많이 사용되는 라이브러리

#### 설치

```bash
!pip install pandas
```

In [46]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\sourcebank\iot-python-2026\iot-venv\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\sourcebank\iot-python-2026\iot-venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\sourcebank\iot-python-2026\iot-venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 275.1 kB/s eta 0:00:34
   -- ------------------------------------- 0.5/9.7 MB 275.1 kB/s eta 0:00:34
   -- ------------------------------------- 0.5/9.7 MB 275.1 kB/s eta 0:00:34
   --- ------------------------------------ 0.8/9.7 MB 313.6 kB/s eta 0:00:29
   --- ------------------------------------ 0.8/9.7 MB 313.6 kB/s eta 0:00:29
   ---- ----------------------------------- 1.0/9.7 MB 387.2 kB/s eta 0:00:23
   ---- ----------------------------------- 1.0/9.7 MB 387.2 kB/s eta 0:00:23
   ---- ----------------------------------- 1.0/9.7 MB 387.2 kB/s eta 0:00:23
   ----- ---------------------------------- 1.3/9.7 MB 397.0 kB/s eta 0:00:22
   ----- ---------------------------------- 1.3/9.7 MB 397.0 kB/s eta 0:00:22
   ----- ---------------------------------- 1.3/9.7 MB 397.0 kB/s eta 0:00:22
   ----- ---------------------------------- 1.3/9.7 MB 397.0 kB/s eta 0:00:22
   ----- ---------------------------------- 1.3/9.7 MB 397.0 kB/s eta 0:00:22
   ----- ---------------------------------- 1.3/9.7 MB 397.0 kB/s eta 0:00:22
   ------ --------------------------------- 1.6/9.7 MB 335.6 kB/s eta 0:00:25
   ------ --------------------------------- 1.6/9.7 MB 335.6 kB/s eta 0:00:25
   ------ --------------------------------- 1.6/9.7 MB 335.6 kB/s eta 0:00:25
   ------- -------------------------------- 1.8/9.7 MB 345.9 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/9.7 MB 345.9 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/9.7 MB 345.9 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/9.7 MB 349.5 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.7 MB 349.5 kB/s eta 0:00:22
   -------- ------------------------------- 2.1/9.7 MB 349.5 kB/s eta 0:00:22
   --------- ------------------------------ 2.4/9.7 MB 357.9 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.7 MB 357.9 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.7 MB 357.9 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.7 MB 357.9 kB/s eta 0:00:21
   --------- ------------------------------ 2.4/9.7 MB 357.9 kB/s eta 0:00:21
   ---------- ----------------------------- 2.6/9.7 MB 349.5 kB/s eta 0:00:21
   ---------- ----------------------------- 2.6/9.7 MB 349.5 kB/s eta 0:00:21
   ---------- ----------------------------- 2.6/9.7 MB 349.5 kB/s eta 0:00:21
   ---------- ----------------------------- 2.6/9.7 MB 349.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.9/9.7 MB 343.8 kB/s eta 0:00:20
   ----------- ---------------------------- 2.9/9.7 MB 343.8 kB/s eta 0:00:20
   ----------- ---------------------------- 2.9/9.7 MB 343.8 kB/s eta 0:00:20
   ----------- ---------------------------- 2.9/9.7 MB 343.8 kB/s eta 0:00:20
   ----------- ---------------------------- 2.9/9.7 MB 343.8 kB/s eta 0:00:20
   ------------ --------------------------- 3.1/9.7 MB 331.9 kB/s eta 0:00:20
   ------------ --------------------------- 3.1/9.7 MB 331.9 kB/s eta 0:00:20
   ------------ --------------------------- 3.1/9.7 MB 331.9 kB/s eta 0:00:20
   ------------ --------------------------- 3.1/9.7 MB 331.9 kB/s eta 0:00:20
   ------------- -------------------------- 3.4/9.7 MB 326.3 kB/s eta 0:00:20
   ------------- -------------------------- 3.4/9.7 MB 326.3 kB/s eta 0:00:20
   ------------- -------------------------- 3.4/9.7 MB 326.3 kB/s eta 0:00:20
   --------------- ------------------------ 3.7/9.7 MB 332.5 kB/s eta 0:00:19
   --------------- ------------------------ 3.7/9.7 MB 332.5 kB/s eta 0:00:19
   --------------- ------------------------ 3.7/9.7 MB 332.5 kB/s eta 0:00:19
   ---------------- ----------------------- 3.9/9.7 MB 340.9 kB/s eta 0:00:18
   ---------------- ----------------------- 3.9/9.7 MB 340.9 kB/s eta 0:00:18
   ----------------- ---------------------- 4.2/9.7 MB 351.5 kB/s eta 0:00:16
   ----------------- ---------------------- 4.2/9.7 MB 351.5 kB/s eta 0:00:16
   ------------------ --------------------- 4.5/9.7 MB 359.8 kB/s eta 0:00:15
   ------------------ --------------------- 4.5/9.7 MB 359.8 kB/s eta 0:00:15
   ------------------ --------------------- 4.5/9.7 MB 359.8 kB/s eta 0:00:15
   ------------------- -------------------- 4.7/9.7 MB 362.9 kB/s eta 0:00:14
   ------------------- -------------------- 4.7/9.7 MB 362.9 kB/s eta 0:00:14
   ------------------- -------------------- 4.7/9.7 MB 362.9 kB/s eta 0:00:14
   -------------------- ------------------- 5.0/9.7 MB 368.3 kB/s eta 0:00:13
   --------------------- ------------------ 5.2/9.7 MB 378.6 kB/s eta 0:00:12
   --------------------- ------------------ 5.2/9.7 MB 378.6 kB/s eta 0:00:12
   ---------------------- ----------------- 5.5/9.7 MB 387.5 kB/s eta 0:00:11
   ---------------------- ----------------- 5.5/9.7 MB 387.5 kB/s eta 0:00:11
   ----------------------- ---------------- 5.8/9.7 MB 395.4 kB/s eta 0:00:11
   ------------------------ --------------- 6.0/9.7 MB 407.4 kB/s eta 0:00:10
   ------------------------- -------------- 6.3/9.7 MB 420.3 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.7 MB 431.6 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.7 MB 442.0 kB/s eta 0:00:07
   --------------------------- ------------ 6.8/9.7 MB 442.0 kB/s eta 0:00:07
   --------------------------- ------------ 6.8/9.7 MB 442.0 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.7 MB 444.2 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.7 MB 444.2 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.7 MB 444.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 443.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 443.2 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.7 MB 443.2 kB/s eta 0:00:06
   ------------------------------- -------- 7.6/9.7 MB 440.7 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.7 MB 440.7 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.7 MB 440.7 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.7 MB 441.9 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.7 MB 450.2 kB/s eta 0:00:04
   --------------------------------- ------ 8.1/9.7 MB 450.2 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.7 MB 453.0 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.7 MB 453.0 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.7 MB 453.0 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 451.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 451.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.7 MB 451.5 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.7 MB 450.5 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 450.5 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 450.5 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 450.5 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 450.5 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 443.9 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 443.9 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 443.9 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 443.9 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.7 MB 435.3 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 435.3 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 435.3 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 435.3 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 435.3 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 435.3 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 422.7 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.7 MB 422.7 kB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 420.1 kB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.1 tzdata-2025.3

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [47]:
!pip list

Package                 Version
----------------------- -----------
asttokens               3.0.1
colorama                0.4.6
comm                    0.2.3
debugpy                 1.8.20
decorator               5.2.1
executing               2.2.1
ipykernel               7.2.0
ipython                 9.12.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
jupyter_client          8.8.0
jupyter_core            5.9.1
matplotlib-inline       0.2.1
nest-asyncio            1.6.0
numpy                   2.4.4
packaging               26.0
pandas                  3.0.1
parso                   0.8.6
pip                     25.0.1
platformdirs            4.9.4
prompt_toolkit          3.0.52
psutil                  7.2.2
pure_eval               0.2.3
Pygments                2.20.0
python-dateutil         2.9.0.post0
pyzmq                   27.1.0
six                     1.17.0
stack-data              0.6.3
tornado                 6.5.5
traitlets               5.14.3
tzdata                  2025.3
wcwidth                 0.6.0

판다스 기초

- 핵심구조
    - DataFrame(데이터프레임): 기준, 2차원 배열
    - Series(시리즈): 최소원소, 1차원 배열

In [48]:
# 판다스 라이브러리 로드
import pandas as pd

In [51]:
# 시리즈
s1 = pd.Series([10, 20, 30])
s1

0    10
1    20
2    30
dtype: int64

In [53]:
# 데이터프레임
# 딕셔너리 타입
data = {
    'name': ['유고', '요미', '철수'],
    'score': [90, 100, 36]
}
data

{'name': ['유고', '요미', '철수'], 'score': [90, 100, 36]}

In [56]:
# 데이터프레임
df = pd.DataFrame(data)
df

  name  score
0   유고     90
1   요미    100
2   철수     36

In [64]:
# CSV 읽기
df = pd.read_csv('./도서정보.csv', encoding='utf-8')
ㅊdf

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [63]:
# 엑셀파일 읽기
df = pd.read_excel('./sample.xlsx')
df

    이름   국어   영어   수학
0  홍길동   95   98   93
1  애슐리  100  100  100

- 엑셀을 읽으려면 openpyxl 모듈이 추가로 필요

```bash
!pip install openpyxl

In [61]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

#### 데이터 확인 및 편집
- 데이터 분석시 필요한 핵심기술

In [ ]:
# CSV 읽기
df = pd.read_csv('./도서정보.csv', encoding='utf-8')
df

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [65]:
# 데이터 확인 - 기본 상위 5개만 출력
df.head()

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실

In [66]:
df.head(3)

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실

In [67]:
# 데이터 하위 다섯 개 출력
df.tail()

,번호,서명,저자,발행자,발행년,청구기호,자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [68]:
# 타입정보 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      10 non-null     int64
 1   서명      10 non-null     str
 2   저자      10 non-null     str
 3   발행자     10 non-null     str
 4   발행년     10 non-null     str
 5   청구기호    10 non-null     str
 6   자료실     10 non-null     str
dtypes: int64(1), str(6)
memory usage: 692.0 bytes

- Null 값은 통계에서 치명적인 데이터
- Null 데이터가 없도록 만들어주는 것이 데이터분석 전 핵심작업

In [71]:
# 기초 통계 기본데이터 추출. 컬럼 중 숫자형만 추출가능
df.describe()

             번호
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000

In [72]:
# 컬럼 선택
df['서명']

0                                해럴드와 마법 크레용 [비디오녹화자료]
1                                  나처럼 예쁜 여자 [비디오녹화자료]
2                                조커 [비디오녹화자료] : 폴리 아 되
3    신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실
4                                  마당을 나온 암탉 [비디오녹화자료]
5                              더 파일럿 [비디오녹화자료] : 드론 어택
6                                   새터데이 나이트 [비디오녹화자료]
7                                구룡성채 [비디오녹화자료] : 무법지대
8            신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀
9                                  베리 미 트와이스 [비디오녹화자료]
Name: 서명, dtype: str

In [73]:
df['서명'].info()

<class 'pandas.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: 서명
Non-Null Count  Dtype
--------------  -----
10 non-null     str
dtypes: str(1)
memory usage: 212.0 bytes

In [75]:
df[['번호', '서명']].info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      10 non-null     int64
 1   서명      10 non-null     str
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

In [76]:
# 새로 데이터프레임 읽기
df = pd.read_excel('./sample.xlsx')
df

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78
3  김예성   50   50.0  100

- NaN: Not a Number

In [77]:
# 국어점수가 60 초과만 필터링
df['국어'] > 60

0     True
1     True
2     True
3    False
Name: 국어, dtype: bool

In [78]:
# 60 초과인 학생 추출
df[df['국어'] > 60]

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   78

In [79]:
# 영어점수가 50 이상 필터링
df['영어'] >= 50

0     True
1     True
2    False
3     True
Name: 영어, dtype: bool

In [80]:
# 영어점수가 50 이상 필터링
df[df['영어'] >= 50]

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
3  김예성   50   50.0  100

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   국어      4 non-null      int64
 2   영어      3 non-null      float64
 3   수학      4 non-null      int64
dtypes: float64(1), int64(2), str(1)
memory usage: 260.0 bytes

In [83]:
# 여기서부터 큰일 발생
df.describe()

               국어          영어          수학
count    4.000000    3.000000    4.000000
mean    83.750000   82.666667   92.750000
std     22.867371   28.307832   10.372239
min     50.000000   50.000000   78.000000
25%     80.000000   74.000000   89.250000
50%     92.500000   98.000000   96.500000
75%     96.250000   99.000000  100.000000
max    100.000000  100.000000  100.000000

#### 결측치(Missing Value)
- 데이터 수집과정에서 누락되거나 측정되지 않은 빈 값
- 데이터 분석에서는 결측치를 처리하는 일이 가장 중요

In [84]:
# 새 컬럼 만들기
df['수학_1'] = df['수학'] - 5

In [86]:
df

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
2  성명건   90    NaN   78    73
3  김예성   50   50.0  100    95

In [87]:
# 오름차순 정렬
df.sort_values('수학_1')

    이름   국어     영어   수학  수학_1
2  성명건   90    NaN   78    73
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95

In [88]:
# 내림차순 정렬
df.sort_values('수학_1', ascending=False)

    이름   국어     영어   수학  수학_1
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95
0  홍길동   95   98.0   93    88
2  성명건   90    NaN   78    73

In [ ]:
# 결측치가 있는 데이터 삭제
df1 =df.dropna()
df1

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
3  김예성   50   50.0  100    95

In [92]:
# 결측치가 있는 값은 모두 같은 값으로 대체
df2 = df.fillna(45)
df2

    이름   국어     영어   수학  수학_1
0  홍길동   95   98.0   93    88
1  애슐리  100  100.0  100    95
2  성명건   90   45.0   78    73
3  김예성   50   50.0  100    95

In [ ]:
# 그룹화(groypby) - SQL이 Group By와 동일
df.groupby('수학').count()

     이름  국어  영어  수학_1
수학
78    1   1   0     1
93    1   1   1     1
100   2   2   2     2

In [ ]:
# 이름같은 str 타입은 통계치를 낼 수 없음
df[['국어', '영어', '수학']].fillna(45).groupby('수학').mean()

       국어    영어
수학
78   90.0  45.0
93   95.0  98.0
100  75.0  75.0

간단 예제

In [96]:
data = {
'name': ['유고', '유미', '철수', '예성'],
'score': [80, 95, 60, 70]
}

df = pd.DataFrame(data)
df

  name  score
0   유고     80
1   유미     95
2   철수     60
3   예성     70

In [97]:
# CSV로 쓰기
df.to_csv('./scores.csv', encoding='utf-8')

In [102]:
df['score'].mean()

np.float64(76.25)

In [100]:
# 70점 이상만 추출
df['score'] > 70

0     True
1     True
2    False
3    False
Name: score, dtype: bool

In [99]:
df[df['score'] >= 70]

  name  score
0   유고     80
1   유미     95
3   예성     70

In [104]:
# 합격여부
# 리스트 컴프리헨션으로 새 컬럼 생성
df['result'] = ['PASS' if s >= 70 else 'FAIL' for s in df['score']]

In [105]:
df

  name  score result
0   유고     80   PASS
1   유미     95   PASS
2   철수     60   FAIL
3   예성     70   PASS

- 판다스 내부는 NumPy 기반임. NumPy 스타일로 처리가능